apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bluebell-aks
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: bluebell-aks
  targetCPUUtilizationPercentage: 50
