{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bluebell.serviceAccountName" . }}
  labels:
{{ include "bluebell.labels" . | indent 4 }}
{{- end -}}
